project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Mickey Rafa"
    left:
      - href: index.qmd
        text: Home
      #- about.qmd
      - href: posts.qmd
        text: Portfolio
      - href: workshops.qmd
        text: Workshops

format:
  html:
    theme:  
      light: minty
      #dark: solar
    css: styles.css
    toc: true
    page-layout: full