project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Mickey Rafa"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:  
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full